services:
  - type: web
    name: mi-frontend
    repo: https://github.com/Betancourt-akm/BronceadoFrontend
    branch: main
    runtime: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
