services:
  - type: static           # en vez de `web` + `runtime: static`, usa directamente static
    name: mi-frontend
    repo: https://github.com/Betancourt-akm/BronceadoFrontend
    branch: main
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: "/*"       # <— atrapa TODO ruta
        destination: "/index.html"
